build-lxd: Simplify code by depending on cache
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/bin/build-lxd b/bin/build-lxd
--- a/bin/build-lxd
+++ b/bin/build-lxd
@@ -20,6 +20,12 @@ cleanup() {
 }
 
 echo "==> SETUP BEGIN"
+echo "===> Sanity checks"
+if [ ! -d "/lxc-ci/build/cache" ]; then
+    echo "Build cache is missing, aborting"
+    exit 1
+fi
+
 echo "===> Creating test environment"
 SUCCESS=0
 TEST_DIR=$(mktemp -d -p /lxc-ci/build/)
@@ -31,34 +37,16 @@ mkdir -p "${TMPDIR}"
 chmod 1777 "${TMPDIR}"
 
 # Setup Go
-if [ "${GO_VERSION}" != "gccgo" ]; then
-    if [ -d /lxc-ci/build/cache ]; then
-        echo "===> Copying a pre-built Go compiler"
+echo "===> Copying a pre-built Go compiler"
 
-        mkdir -p "${TEST_DIR}/go"
-        export GOROOT=${TEST_DIR}/go/golang/
-        export PATH=${GOROOT}/bin:$PATH
+mkdir -p "${TEST_DIR}/go"
+export GOROOT=${TEST_DIR}/go/golang/
+export PATH=${GOROOT}/bin:$PATH
 
-        if [ "${GO_VERSION}" = "golang-tip" ]; then
-            cp -Ra /lxc-ci/build/cache/gimme/versions/go/ "${GOROOT}"
-        else
-            cp -Ra /lxc-ci/build/cache/gimme/versions/go*"${GO_VERSION#golang-}"*/ "${GOROOT}"
-        fi
-    else
-        echo "===> Downloading the Go compiler"
-
-        [ "$(arch)" != "i686" ] || export GIMME_ARCH=x86
-        export GIMME_ENV_PREFIX=${TEST_DIR}/go/envs/
-        export GIMME_VERSION_PREFIX=${TEST_DIR}/go/versions/
-
-        cd /lxc-ci/deps/gimme/ || exit 1
-        [ "${GO_VERSION}" = "golang-tip" ] && ./gimme 1.8
-        ./gimme "${GO_VERSION#golang-}" >/dev/null
-        cd -
-        . "${GIMME_ENV_PREFIX}/go${GO_VERSION#golang-}.env" 2>/dev/null
-    fi
+if [ "${GO_VERSION}" = "golang-tip" ]; then
+    cp -Ra /lxc-ci/build/cache/gimme/versions/go/ "${GOROOT}"
 else
-    echo "===> Using the system Go compiler"
+    cp -Ra /lxc-ci/build/cache/gimme/versions/go*"${GO_VERSION#golang-}"*/ "${GOROOT}"
 fi
 
 # Setup build environment
@@ -66,19 +54,19 @@ echo "===> Setting up environment variables"
 mkdir -p "${TEST_DIR}/go"
 export GOPATH=${TEST_DIR}/go
 export PATH=${PATH}:${GOPATH}/bin
-if [ -d "/lxc-ci/build/cache" ]; then
-    echo "===> Copying pre-built dependencies"
-    VERSION=$(go version | cut -d' ' -f3)
-    [ -d "/lxc-ci/build/cache/go/bin.${VERSION}" ] && cp -Ra "/lxc-ci/build/cache/go/bin.${VERSION}" "${GOPATH}/bin"
-    [ -d "/lxc-ci/build/cache/go/pkg.${VERSION}" ] && cp -Ra "/lxc-ci/build/cache/go/pkg.${VERSION}" "${GOPATH}/pkg"
-    [ -d "/lxc-ci/build/cache/go/src" ] && cp -Ra /lxc-ci/build/cache/go/src "${GOPATH}/src"
-fi
+
+# Setup dependencies
+echo "===> Copying pre-built dependencies"
+VERSION=$(go version | cut -d' ' -f3)
+[ -d "/lxc-ci/build/cache/go/bin.${VERSION}" ] && cp -Ra "/lxc-ci/build/cache/go/bin.${VERSION}" "${GOPATH}/bin"
+[ -d "/lxc-ci/build/cache/go/pkg.${VERSION}" ] && cp -Ra "/lxc-ci/build/cache/go/pkg.${VERSION}" "${GOPATH}/pkg"
+[ -d "/lxc-ci/build/cache/go/src" ] && cp -Ra /lxc-ci/build/cache/go/src "${GOPATH}/src"
 
 # Setup Git
 mkdir -p "${GOPATH}/src/github.com/lxc"
 rm -Rf "${GOPATH}/src/github.com/lxc/lxd"
 if [ -n "${WORKSPACE:-}" ]; then
-    echo "===> Copying the Jenkins git reository"
+    echo "===> Copying the Jenkins git repository"
     cp -R "${WORKSPACE}" "${GOPATH}/src/github.com/lxc/lxd"
     cd "${GOPATH}/src/github.com/lxc/lxd"
 else
@@ -95,7 +83,7 @@ echo "==> ENVIRONMENT BEGIN"
 
 # Clustering
 if [ -e "lxd/cluster" ]; then
-    echo "===> Detected LXD clustering"
+    echo "===> Setting up for LXD clustering"
     export CGO_CFLAGS="-I/lxc-ci/build/cache/sqlite/"
     export CGO_LDFLAGS="-L/lxc-ci/build/cache/sqlite/.libs/"
     export LD_LIBRARY_PATH="/lxc-ci/build/cache/sqlite/.libs/"
@@ -111,14 +99,14 @@ echo "==> ENVIRONMENT DONE"
 
 # Build LXD
 echo "==> BUILD BEGIN: lxd"
-go get -t -v -x -d ./...
-go install -v -x -tags libsqlite3 ./...
+go get -t -d ./...
+go install -tags libsqlite3 ./...
 echo "==> BUILD DONE: lxd"
 
 # Run the unit tests
 if [ "${LXD_BACKEND}" = "dir" ]; then
     echo "==> UNIT BEGIN: all tests"
-    go test -v -tags libsqlite3 ./...
+    go test -tags libsqlite3 ./...
     echo "==> UNIT DONE: all tests"
 fi
 
