maas-run: Deal with already allocated machines
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/bin/maas-run b/bin/maas-run
--- a/bin/maas-run
+++ b/bin/maas-run
@@ -12,7 +12,27 @@ maas login maas "${MAAS_URL}" "${MAAS_API}" >/dev/null
 
 # Allocate a machine
 echo "==> Allocating a machine"
-system_id=$(maas maas machines allocate "${1}" | jq -r .system_id)
+while :; do
+    TMPFILE=$(mktemp)
+
+    set +e
+    maas maas machines allocate "${1}" > "${TMPFILE}" 2>&1
+    RET=$?
+    if [ "${RET}" = "2" ]; then
+        echo "===> System is currently busy, trying again in 60s"
+        sleep 60
+        continue
+    elif [ "${RET}" != "0" ]; then
+        echo "===> Failed to allocate"
+        cat "${TMPFILE}"
+        rm "${TMPFILE}"
+    fi
+    set -e
+
+    break
+done
+
+system_id=$(jq -r .system_id < "${TMPFILE}")
 
 # Release on exit
 RET=1
