bin/test-lxd-network-ovn: Adds tests for OVN network peering
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

diff --git a/bin/test-lxd-network-ovn b/bin/test-lxd-network-ovn
--- a/bin/test-lxd-network-ovn
+++ b/bin/test-lxd-network-ovn
@@ -739,6 +739,225 @@ EOF
     lxc network delete lxdbr0
 }
 
+ovn_peering_tests() {
+    # Create two projects to test cross-project peering.
+    lxc project create ovn1 \
+        -c features.images=false \
+        -c features.profiles=false \
+        -c features.storage.volumes=false \
+        -c features.networks=true
+
+    lxc project create ovn2 \
+        -c features.images=false \
+        -c features.profiles=false \
+        -c features.storage.volumes=false \
+        -c features.networks=true
+
+    # Create lxdbr0 bridge to act as uplink network with some uplink routes that can be used.
+    lxc network create lxdbr0 \
+        ipv4.address=10.10.10.1/24 ipv4.nat=true \
+        ipv4.dhcp.ranges=10.10.10.2-10.10.10.199 \
+        ipv4.ovn.ranges=10.10.10.200-10.10.10.254 \
+        ipv6.address=fd42:4242:4242:1010::1/64 ipv6.nat=true \
+        ipv6.ovn.ranges=fd42:4242:4242:1010::200-fd42:4242:4242:1010::254 \
+        ipv4.routes=198.51.100.0/24 \
+        ipv6.routes=2001:db8:1:2::/64
+
+    # Create OVN networks in each project.
+    lxc network create ovn1 --type=ovn network=lxdbr0 --project=ovn1
+    lxc network create ovn2 --type=ovn network=lxdbr0 --project=ovn2
+    sleep 2
+
+    lxc network show ovn1 --project=ovn1
+    lxc network show ovn2 --project=ovn2
+
+    ovn1NetIPv4=$(lxc network get ovn1 ipv4.address --project=ovn1 | sed 's/\/24$//g')
+    ovn1NetIPv6=$(lxc network get ovn1 ipv6.address --project=ovn1 | sed 's/\/64$//g')
+    ovn2NetIPv4=$(lxc network get ovn2 ipv4.address --project=ovn2 | sed 's/\/24$//g')
+    ovn2NetIPv6=$(lxc network get ovn2 ipv6.address --project=ovn2 | sed 's/\/64$//g')
+
+    # Now setup peering.
+    lxc network peer create ovn1 ovn1foo ovn2/ovn2 --project=ovn1
+    lxc network peer ls ovn1 --project=ovn1 | grep ovn1foo | grep PENDING
+    lxc network peer create ovn2 ovn2foo ovn1/ovn1 --project=ovn2
+    lxc network peer ls ovn1 --project=ovn1 | grep ovn1foo | grep CREATED
+    lxc network peer ls ovn2 --project=ovn2 | grep ovn2foo | grep CREATED
+
+    # Check networks show as in use by peered network.
+    lxc network show ovn1 --project=ovn1 | grep ovn2
+    lxc network show ovn2 --project=ovn2 | grep ovn1
+
+    # Check network delete is protected by peer usage.
+    ! lxc network delete ovn1 --project=ovn1 || false
+    ! lxc network delete ovn2 --project=ovn2 || false
+
+    # Delete peering.
+    lxc network peer delete ovn1 ovn1foo --project=ovn1
+    lxc network peer ls ovn2 --project=ovn2 | grep ovn2foo | grep ERRORED
+    ! lxc network show ovn1 --project=ovn1 | grep ovn2 || false
+    ! lxc network show ovn2 --project=ovn2 | grep ovn1 || false
+
+    # Launch instance in each network (with one having NIC routes from uplink).
+    lxc init images:ubuntu/20.04 ovn1 -n ovn1 -s default --project=ovn1
+    lxc config device set ovn1 eth0 --project=ovn1 \
+        ipv4.routes=198.51.100.1/32 \
+        ipv6.routes=2001:db8:1:2::1/128 \
+        ipv4.routes.external=198.51.100.2/32 \
+        ipv6.routes.external=2001:db8:1:2::2/128
+    lxc start ovn1 --project=ovn1
+    lxc launch images:ubuntu/20.04 ovn2 -n ovn2 -s default --project=ovn2
+
+    # Add IPs from routes to ovn1 instance.
+    sleep 2
+    lxc exec ovn1 --project=ovn1 -- ip a add 198.51.100.1/32 dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a add 198.51.100.2/32 dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a add 2001:db8:1:2::1/128 dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a add 2001:db8:1:2::2/128 dev eth0
+
+    # Test that pinging internal addresses between networks doesn't work without peering.
+    sleep 5
+    ! lxc exec ovn1 --project=ovn1 -- ping -c1 -4 -W5 "${ovn2NetIPv4}" || false
+    ! lxc exec ovn1 --project=ovn1 -- ping -c1 -6 -W5 "${ovn2NetIPv6}" || false
+    ! lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 198.51.100.1 || false
+    ! lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 2001:db8:1:2::1 || false
+
+    # Test that pinging external addresses between networks does worth without peering (goes via uplink).
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 198.51.100.2
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 2001:db8:1:2::2
+
+    # Remove routes on uplink manually to purposefully break uplink routing of external routes.
+    ip -4 r del 198.51.100.0/24 dev lxdbr0
+    ip -6 r del 2001:db8:1:2::/64 dev lxdbr0
+
+    # Test that pinging external addresses between networks doesn't worth via uplink with removed routes.
+    ! lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 198.51.100.2 || false
+    ! lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 2001:db8:1:2::2 || false
+
+    # Now setup peering again.
+    lxc network peer create ovn1 ovn1foo ovn2/ovn2 --project=ovn1
+    ! lxc network peer create ovn2 ovn2foo ovn1/ovn1 --project=ovn2 || false # Detect old peering entry exists.
+    lxc network peer delete ovn2 ovn2foo --project=ovn2 # Delete old peering entry.
+    lxc network peer create ovn2 ovn2foo ovn1/ovn1 --project=ovn2
+    lxc network peer ls ovn2 --project=ovn2 | grep ovn2foo | grep CREATED
+
+    # Test that pinging now works between networks.
+    sleep 5
+
+    # Ping gateways on each peer endpoint.
+    lxc exec ovn1 --project=ovn1 -- ping -c1 -4 -W5 "${ovn2NetIPv4}"
+    lxc exec ovn1 --project=ovn1 -- ping -c1 -6 -W5 "${ovn2NetIPv6}"
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 "${ovn1NetIPv4}"
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 "${ovn1NetIPv6}"
+
+    # Ping internal and external NIC route addresses over peer connection.
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 198.51.100.1
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 2001:db8:1:2::1
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -4 -W5 198.51.100.2
+    lxc exec ovn2 --project=ovn2 -- ping -c1 -6 -W5 2001:db8:1:2::2
+
+    # Check address set entries added for running instances.
+    ovn-nbctl list address_set | grep 198.51.100.1/32
+    ovn-nbctl list address_set | grep 2001:db8:1:2::1/128
+    ovn-nbctl list address_set | grep 198.51.100.2/32
+    ovn-nbctl list address_set | grep 2001:db8:1:2::2/128
+
+    # Check address set entries deleted for instance NIC when stopped and added when started again.
+    lxc stop -f ovn1 --project=ovn1
+    ! ovn-nbctl list address_set | grep 198.51.100.1/32 || false
+    ! ovn-nbctl list address_set | grep 2001:db8:1:2::1/128 || false
+    ! ovn-nbctl list address_set | grep 198.51.100.2/32 || false
+    ! ovn-nbctl list address_set | grep 2001:db8:1:2::2/128 || false
+    lxc start ovn1 --project=ovn1
+    ovn-nbctl list address_set | grep 198.51.100.1/32
+    ovn-nbctl list address_set | grep 2001:db8:1:2::1/128
+    ovn-nbctl list address_set | grep 198.51.100.2/32
+    ovn-nbctl list address_set | grep 2001:db8:1:2::2/128
+
+    # Check security policies prevent spoofed packets using peer connection.
+    sleep 5
+    ovn1NICIPv4="$(lxc list ovn1 -c4 --format=csv --project=ovn1 | cut -d' ' -f1)"
+    ovn1NICIPv6="$(lxc list ovn1 -c6 --format=csv --project=ovn1 | cut -d' ' -f1)"
+    ovn2NICIPv4="$(lxc list ovn2 -c4 --format=csv --project=ovn2 | cut -d' ' -f1)"
+    ovn2NICIPv6="$(lxc list ovn2 -c6 --format=csv --project=ovn2 | cut -d' ' -f1)"
+
+    # Install tcpdump and check we can detect ICMP packets coming to the ovn2 instance from ovn1 instance when
+    # pinging the allowed addresses.
+    lxc exec ovn2 --project=ovn2 -- apt install tcpdump -y
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -4 -W5 "${ovn2NICIPv4}" || true &
+    lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp and src ${ovn1NICIPv4} -q -c 1 > /dev/null
+    wait
+
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -6 -W5 "${ovn2NICIPv6}" || true &
+    lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp6 and src ${ovn1NICIPv6} -q -c 1 > /dev/null
+    wait
+
+    # Now reconfigure ovn1's IP address inside the instance to an unknown IP and try pinging ovn2.
+    # Check that the security policies prevent those ICMP packets from reaching ovn2 instance.
+    # Disable DHCP client and SLAAC acceptance so we don't get automatic IPs added.
+    lxc exec ovn1 --project=ovn1 -- rm -f /etc/netplan/*
+    lxc exec ovn1 --project=ovn1 -- netplan apply
+    lxc exec ovn1 --project=ovn1 -- sysctl net.ipv6.conf.eth0.accept_ra=0
+    lxc exec ovn1 --project=ovn1 -- sysctl net.ipv6.conf.eth0.autoconf=0
+    lxc exec ovn1 --project=ovn1 -- ip a flush dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a add 198.51.100.3/32 dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a add 2001:db8:1:2::3/128 dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip a
+    sleep 2
+    lxc exec ovn1 --project=ovn1 -- ip -4 r add "${ovn1NetIPv4}" dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip -4 r add default via "${ovn1NetIPv4}" dev eth0 src 198.51.100.3
+    lxc exec ovn1 --project=ovn1 -- ip -6 r add "${ovn1NetIPv6}" dev eth0
+    lxc exec ovn1 --project=ovn1 -- ip -6 r add default via "${ovn1NetIPv6}" dev eth0 src 2001:db8:1:2::3
+    lxc exec ovn1 --project=ovn1 -- ip -4 r
+    lxc exec ovn1 --project=ovn1 -- ip -6 r
+
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -4 -W5 "${ovn2NICIPv4}" || true &
+    ! lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp and src 198.51.100.3 -q -c 1 > /dev/null || false
+    wait
+
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -6 -W5 "${ovn2NICIPv6}" || true &
+    ! lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp6 and src 2001:db8:1:2::3 -q -c 1 > /dev/null || false
+    wait
+
+    # Clear all security rules and check spoofed packets are recieved to prove the security rules were working.
+    ovn-nbctl lr-list
+    ovn1NetID=$(lxd sql global 'select id from networks where name = "ovn1"' | grep -Po '\d+')
+    ovn2NetID=$(lxd sql global 'select id from networks where name = "ovn2"' | grep -Po '\d+')
+
+    ovn-nbctl lr-policy-del "lxd-net${ovn1NetID}-lr"
+    ovn-nbctl lr-policy-del "lxd-net${ovn2NetID}-lr"
+
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -4 -W5 "${ovn2NICIPv4}" || true &
+    lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp and src 198.51.100.3 -q -c 1 > /dev/null
+    wait
+
+    lxc exec ovn1 -T -n --project=ovn1 -- ping -c3 -6 -W5 "${ovn2NICIPv6}" || true &
+    lxc exec ovn2 -T -n --project=ovn2 -- timeout 5s tcpdump -i eth0 -nn icmp6 and src 2001:db8:1:2::3 -q -c 1 > /dev/null
+    wait
+
+    # Check changing the network's subnet is reflected in the address sets and peering routes and the old subnets
+    # are removed.
+    lxc delete -f ovn1 --project=ovn1 # Remove as we cleared its DHCP config.
+    lxc network set ovn1 ipv4.address=192.0.2.1/24 ipv6.address=2001:db8:1:1::1/64 --project=ovn1
+    lxc launch images:ubuntu/20.04 ovn1 -n ovn1 -s default --project=ovn1
+    sleep 5
+    ovn1NICIPv4="$(lxc list ovn1 -c4 --format=csv --project=ovn1 | cut -d' ' -f1)"
+    ovn1NICIPv6="$(lxc list ovn1 -c6 --format=csv --project=ovn1 | cut -d' ' -f1)"
+    lxc exec ovn2 -T -n --project=ovn2 -- ping -c1 -4 -W5 "${ovn1NICIPv4}"
+    lxc exec ovn2 -T -n --project=ovn2 -- ping -c1 -6 -W5 "${ovn1NICIPv6}"
+
+    # Cleanup.
+    lxc delete -f ovn1 --project=ovn1
+    lxc delete -f ovn2 --project=ovn2
+
+    lxc network peer delete ovn1 ovn1foo --project=ovn1
+    lxc network delete ovn1 --project=ovn1
+    lxc network delete ovn2 --project=ovn2
+    lxc network delete lxdbr0
+
+    lxc project delete ovn1
+    lxc project delete ovn2
+}
+
 # Allow for running a specific set of tests.
 if [ "$#" -gt 0 ]; then
   TEST_CURRENT="ovn_${1}_tests"
@@ -747,6 +966,7 @@ else
     # Otherwise run full suite.
     ovn_basic_tests
     ovn_forward_tests
+    ovn_peering_tests
 fi
 
 lxc storage delete default
