images: Workaround IMA attribute for Oracle
Signed-off-by: Stéphane Graber <stgraber@stgraber.org>

diff --git a/images/oracle.yaml b/images/oracle.yaml
--- a/images/oracle.yaml
+++ b/images/oracle.yaml
@@ -239,3 +239,14 @@ actions:
 
     # Disable loginuid in PAM stack
     sed -i '/^session.*pam_loginuid.so/s/^session/# session/' /etc/pam.d/*
+
+# workaround for https://discuss.linuxcontainers.org/t/help-needed-failed-to-launch-the-lxd-container/15674/6
+- trigger: post-files
+  action: |-
+    #!/bin/sh
+    set -eu
+    for f in $(find /etc/dnf/protected.d/ -type f); do
+      setfattr -x security.ima "${f}" >/dev/null 2>&1 || true
+    done
+  types:
+  - container
